config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts  do
    collection do
      get 'search'
    end
  end
  root 'posts#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user! , except: [:show, :index]
    
    def index
        @posts =  Post.all

        @q = Post.ransack(params[:q])
        @posts= @q.result
        @post = Post.new

        
    end

    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)
        post.user_id = current_user.id

        if post.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
            redirect_to :action => "show", :id => post.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end


    
    private

    def post_params
        params.require(:post).permit(:title, :datedate, :contents ,:image , :uno , :dos ,:tres, tag_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ransackお遊び用</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>posts#edit</h1>
<%= form_for @post do |f| %>
    <%= f.label :title %>
    <p><%= f.text_field :title, :size => 50 %></p>
    <%= f.label :image %>
    <p><%= f.file_field :image %></p>
    <%= f.label :contents %>
    <p><%= f.text_field :contents, :size => 50 %></p>
    <%= f.submit "編集する" %>
<% end %>

app/views/posts/index.html.erb
<h1>posts#index</h1>

<%= search_form_for @q  do |f| %>
    <p><%= f.label :値段 %>
    <%= f.select :uno_cont, [['~1000円', '~1000円、'], ['1000~2000円', '1000~2000円、'], ['2000円~', '2000円~、']], {include_blank: '値段'} %>
    <%= f.label :評価 %>
    <%= f.select :dos_cont, [['最高', '最高、'], ['普通', '普通、'], ['アカーン', 'アカーン、']] , {include_blank: '評価'} %>
    <%= f.label :拠点 %>
    <%= f.select :tres_cont, [['京都', '京都'], ['大阪', '大阪'], ['神戸', '神戸']] , {include_blank: '拠点'} %>
    <%= f.search_field :title_or_contents_cont %>
    <%= f.submit "search" %></p>
<% end %>



<% if user_signed_in? %>    
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% end %>
<%= link_to "新規投稿へ", new_post_path %>
<div class="posts-container">
    <% @posts.each do |t| %>
            <div class="post">
                <% if t.title.blank? %>
                    <p>タイトルありまへん</p>
                <% else %>
                    <p><%= t.title %></p>
                <% end %>
                
                <p><%= t.datedate.to_s(:datetime_jp) %></p>
                <!--
                    <p>
                        <% if t.image.present? %>
                            <%= image_tag t.image_url, size: '250x200'%>
                        <% else %>
                            <%= image_tag "noimage.png", size: '250x200' %>
                        <% end %>
                    </p>
                -->
                <p><%= t.contents %></p>


                <p>
                    <%= t.uno %>
                    <%= t.dos %>
                    <%= t.tres %>
                </p>
                <div class="post_option"> 
                    <% if user_signed_in? && current_user.id == t.user_id %>
                        <%= link_to edit_post_path(t.id) , method: :get do %>
                            <i class="far fa-edit"></i>
                        <% end %>
                        <%= link_to post_path(t.id), method: :delete do %>
                            <i class="fas fa-trash-alt"></i>
                        <% end %>
                    <% end %>
                </div>
            </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>posts#new</h1>
<div class="newall">
    <%= form_for @post do |f| %>
        <div class="post-new">
            <p><%= f.label :title %></p>
            <p><%= f.text_field :title, :size => 50 %></p>
            <p><%= f.label :image %></p>
            <p><%= f.file_field :image %></p>
            <p><%= f.datetime_field :datedate , {discard: true} %></p>
            <!--
            <div class="check_box">
                <span>タグ</span>
                <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                    <div>
                    <%= tag.label do %>
                        <%= tag.check_box %>
                        <%= tag.text %>
                    <% end %>
                    </div>
                <% end %>
            </div>
            -->
            <p><%= f.select :uno, [['値段', ''], ['~1000円', 'aiu'], ['1000~2000円', 'eo'], ['2000円~', 'ka']] %></p>
            <p><%= f.select :dos, [['評価', ''], ['最高', '最高、'], ['普通', '普通、'], ['アカーン', 'アカーン、']] %></p>
            <p><%= f.select :tres, [['拠点', ''], ['京都', '京都'], ['大阪', '大阪'], ['神戸', '神戸']] %></p>
            <p><%= f.label :contents %></p>
            <p><%= f.text_field :contents, :size => 50 %></p>
        </div>
        <%= f.submit "postする" %>
    <% end %>
</div>
<%= link_to "post一覧に戻る", posts_path %>

app/views/posts/search.html.erb
<h1>検索結果だお</h1>

<% @results.each do |t| %>
        <div class="search">
            <% if t.title.blank? %>
                <p>タイトルありまへん</p>
            <% else %>
                <p><%= t.title %></p>
            <% end %>
                <p>
                    <% if t.image.present? %>
                        <%= image_tag t.image_url, size: '250x200'%>
                    <% else %>
                        <%= image_tag "noimage.png", size: '250x200' %>
                    <% end %>
                </p>
            <p><%= t.contents %></p>
            <p>
                <%= t.uno %>
                <%= t.dos %>
                <%= t.tres %>
            </p>
            <div class="post_option"> 
                <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to edit_post_path(t.id) , method: :get do %>
                        <i class="far fa-edit"></i>
                    <% end %>
                    <%= link_to post_path(t.id), method: :delete do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                <% end %>
                <%= link_to post_path(t.id), method: :get do %>
                    <i class="fas fa-arrow-circle-right"></i>
                <% end %>
            </div>
        </div>
    <% end %>

    <%= link_to 'Top', posts_path %>

app/views/posts/show.html.erb
<h1>posts#show</h1>
    <div class="post-show">
        <p><%= @post.title %></p>
            <p>
                <% if @post.image.present? %>
                    <%= image_tag @post.image_url, size: '250x200'%>
                <% else %>
                    <%= image_tag "noimage.png", size: '250x200' %>
                <% end %>
            </p>
        <p><%= @post.contents %></p>
        <p><%= @post.uno %></p>
        <p><%= @post.dos %></p>
        <p><%= @post.tres %></p>
    </div>
    
<%= link_to "編集する", edit_post_path(@post.id) %>
<%= link_to "post一覧に戻る", posts_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>